---
- name: Gathering Facts
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
  - block:
    - name: Setting proxy
      set_fact:
        proxy_env: {
                   "https_proxy": "https://{{ proxy_user }}:{{ proxy_passwd }}@{{ proxy_server }}:{{ proxy_port }}",
                   "http_proxy": "http://{{ proxy_user }}:{{ proxy_passwd }}@{{ proxy_server }}:{{ proxy_port }}"
                 }
      when: proxy_optional
    
    - name: Edit hive_site.xml template
      template:
        src: roles/hive/templates/hive_site.j2
        dest: "{{ hadoop_dir }}/apache-hive-{{ hive_version }}-bin/conf/hive-site.xml"
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
