---
- name: Uninstall git if present
  package: name=git state=absent

- name: Create Git Dir
  file: path={{ git_install_path }}/bin state=directory

- name: Create Git local Path
  file: path={{ git_local_dir }} state=directory

- name: Download Git
  shell: "wget {{ git_mirror_download }} -P {{ git_local_dir }} --no-check-certificate"

- name: Extract Git
  shell: "tar -zxvf {{ git_local_path }} -C {{ git_install_path }}"

- name: Compile Git
  shell: cd {{ git_install_path }}/git-{{ git_version }} ; make prefix={{ git_install_path }} all

- name: Make Git binary
  shell: cd {{ git_install_path }}/git-{{ git_version }} ; make prefix={{ git_install_path }} install

- name: Cleanup post git build
  file: path={{ git_install_path }}/git-{{ git_version }} state=absent

- name: Set GIT_HOME
  template: src=git_path.j2 dest={{ git_profile_path }} mode=0755
